// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xtestflow.h"

extern XTestflow_Config XTestflow_ConfigTable[];

XTestflow_Config *XTestflow_LookupConfig(u16 DeviceId) {
	XTestflow_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XTESTFLOW_NUM_INSTANCES; Index++) {
		if (XTestflow_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XTestflow_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XTestflow_Initialize(XTestflow *InstancePtr, u16 DeviceId) {
	XTestflow_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XTestflow_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XTestflow_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

