// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XGREYSCALE_H
#define XGREYSCALE_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xgreyscale_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XGreyscale_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XGreyscale;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XGreyscale_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XGreyscale_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XGreyscale_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XGreyscale_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XGreyscale_Initialize(XGreyscale *InstancePtr, u16 DeviceId);
XGreyscale_Config* XGreyscale_LookupConfig(u16 DeviceId);
int XGreyscale_CfgInitialize(XGreyscale *InstancePtr, XGreyscale_Config *ConfigPtr);
#else
int XGreyscale_Initialize(XGreyscale *InstancePtr, const char* InstanceName);
int XGreyscale_Release(XGreyscale *InstancePtr);
#endif

void XGreyscale_Start(XGreyscale *InstancePtr);
u32 XGreyscale_IsDone(XGreyscale *InstancePtr);
u32 XGreyscale_IsIdle(XGreyscale *InstancePtr);
u32 XGreyscale_IsReady(XGreyscale *InstancePtr);
void XGreyscale_EnableAutoRestart(XGreyscale *InstancePtr);
void XGreyscale_DisableAutoRestart(XGreyscale *InstancePtr);

u32 XGreyscale_Get_pixelInput_BaseAddress(XGreyscale *InstancePtr);
u32 XGreyscale_Get_pixelInput_HighAddress(XGreyscale *InstancePtr);
u32 XGreyscale_Get_pixelInput_TotalBytes(XGreyscale *InstancePtr);
u32 XGreyscale_Get_pixelInput_BitWidth(XGreyscale *InstancePtr);
u32 XGreyscale_Get_pixelInput_Depth(XGreyscale *InstancePtr);
u32 XGreyscale_Write_pixelInput_Words(XGreyscale *InstancePtr, int offset, int *data, int length);
u32 XGreyscale_Read_pixelInput_Words(XGreyscale *InstancePtr, int offset, int *data, int length);
u32 XGreyscale_Write_pixelInput_Bytes(XGreyscale *InstancePtr, int offset, char *data, int length);
u32 XGreyscale_Read_pixelInput_Bytes(XGreyscale *InstancePtr, int offset, char *data, int length);
u32 XGreyscale_Get_pixelOutput_BaseAddress(XGreyscale *InstancePtr);
u32 XGreyscale_Get_pixelOutput_HighAddress(XGreyscale *InstancePtr);
u32 XGreyscale_Get_pixelOutput_TotalBytes(XGreyscale *InstancePtr);
u32 XGreyscale_Get_pixelOutput_BitWidth(XGreyscale *InstancePtr);
u32 XGreyscale_Get_pixelOutput_Depth(XGreyscale *InstancePtr);
u32 XGreyscale_Write_pixelOutput_Words(XGreyscale *InstancePtr, int offset, int *data, int length);
u32 XGreyscale_Read_pixelOutput_Words(XGreyscale *InstancePtr, int offset, int *data, int length);
u32 XGreyscale_Write_pixelOutput_Bytes(XGreyscale *InstancePtr, int offset, char *data, int length);
u32 XGreyscale_Read_pixelOutput_Bytes(XGreyscale *InstancePtr, int offset, char *data, int length);

void XGreyscale_InterruptGlobalEnable(XGreyscale *InstancePtr);
void XGreyscale_InterruptGlobalDisable(XGreyscale *InstancePtr);
void XGreyscale_InterruptEnable(XGreyscale *InstancePtr, u32 Mask);
void XGreyscale_InterruptDisable(XGreyscale *InstancePtr, u32 Mask);
void XGreyscale_InterruptClear(XGreyscale *InstancePtr, u32 Mask);
u32 XGreyscale_InterruptGetEnabled(XGreyscale *InstancePtr);
u32 XGreyscale_InterruptGetStatus(XGreyscale *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
