// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xgreyscale.h"

extern XGreyscale_Config XGreyscale_ConfigTable[];

XGreyscale_Config *XGreyscale_LookupConfig(u16 DeviceId) {
	XGreyscale_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XGREYSCALE_NUM_INSTANCES; Index++) {
		if (XGreyscale_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XGreyscale_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XGreyscale_Initialize(XGreyscale *InstancePtr, u16 DeviceId) {
	XGreyscale_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XGreyscale_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XGreyscale_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

