# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/Users/mathi/Desktop/Kandidat/Embedded/Project/testings/TestPorject/solution1/impl/vhdl/greyScale.xdc

# IP: ip/greyScale_ap_sitodp_4_no_dsp_32/greyScale_ap_sitodp_4_no_dsp_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==greyScale_ap_sitodp_4_no_dsp_32 || ORIG_REF_NAME==greyScale_ap_sitodp_4_no_dsp_32}]

# IP: ip/greyScale_ap_dmul_4_max_dsp_64/greyScale_ap_dmul_4_max_dsp_64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==greyScale_ap_dmul_4_max_dsp_64 || ORIG_REF_NAME==greyScale_ap_dmul_4_max_dsp_64}]

# IP: ip/greyScale_ap_dadd_3_full_dsp_64/greyScale_ap_dadd_3_full_dsp_64.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==greyScale_ap_dadd_3_full_dsp_64 || ORIG_REF_NAME==greyScale_ap_dadd_3_full_dsp_64}]
