# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/mathi/Desktop/Kandidat/Embedded/Project/testings/TestPorject/solution1/impl/vhdl/project.cache/wt [current_project]
set_property parent.project_path C:/Users/mathi/Desktop/Kandidat/Embedded/Project/testings/TestPorject/solution1/impl/vhdl/project.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/mathi/Desktop/Kandidat/Embedded/Project/testings/TestPorject/solution1/impl/vhdl/project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/mathi/Desktop/Kandidat/Embedded/Project/testings/TestPorject/solution1/impl/vhdl/greyScale.vhd
  C:/Users/mathi/Desktop/Kandidat/Embedded/Project/testings/TestPorject/solution1/impl/vhdl/greyScale_AXILiteS_s_axi.vhd
  C:/Users/mathi/Desktop/Kandidat/Embedded/Project/testings/TestPorject/solution1/impl/vhdl/greyScale_dadd_64bkb.vhd
  C:/Users/mathi/Desktop/Kandidat/Embedded/Project/testings/TestPorject/solution1/impl/vhdl/greyScale_dmul_64cud.vhd
  C:/Users/mathi/Desktop/Kandidat/Embedded/Project/testings/TestPorject/solution1/impl/vhdl/greyScale_sitodp_dEe.vhd
}
read_ip -quiet c:/Users/mathi/Desktop/Kandidat/Embedded/Project/testings/TestPorject/solution1/impl/vhdl/project.srcs/sources_1/ip/greyScale_ap_sitodp_4_no_dsp_32/greyScale_ap_sitodp_4_no_dsp_32.xci
set_property is_locked true [get_files c:/Users/mathi/Desktop/Kandidat/Embedded/Project/testings/TestPorject/solution1/impl/vhdl/project.srcs/sources_1/ip/greyScale_ap_sitodp_4_no_dsp_32/greyScale_ap_sitodp_4_no_dsp_32.xci]

read_ip -quiet c:/Users/mathi/Desktop/Kandidat/Embedded/Project/testings/TestPorject/solution1/impl/vhdl/project.srcs/sources_1/ip/greyScale_ap_dmul_4_max_dsp_64/greyScale_ap_dmul_4_max_dsp_64.xci
set_property is_locked true [get_files c:/Users/mathi/Desktop/Kandidat/Embedded/Project/testings/TestPorject/solution1/impl/vhdl/project.srcs/sources_1/ip/greyScale_ap_dmul_4_max_dsp_64/greyScale_ap_dmul_4_max_dsp_64.xci]

read_ip -quiet c:/Users/mathi/Desktop/Kandidat/Embedded/Project/testings/TestPorject/solution1/impl/vhdl/project.srcs/sources_1/ip/greyScale_ap_dadd_3_full_dsp_64/greyScale_ap_dadd_3_full_dsp_64.xci
set_property is_locked true [get_files c:/Users/mathi/Desktop/Kandidat/Embedded/Project/testings/TestPorject/solution1/impl/vhdl/project.srcs/sources_1/ip/greyScale_ap_dadd_3_full_dsp_64/greyScale_ap_dadd_3_full_dsp_64.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/mathi/Desktop/Kandidat/Embedded/Project/testings/TestPorject/solution1/impl/vhdl/greyScale.xdc
set_property used_in_implementation false [get_files C:/Users/mathi/Desktop/Kandidat/Embedded/Project/testings/TestPorject/solution1/impl/vhdl/greyScale.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top greyScale -part xc7z010clg400-1 -no_iobuf -mode out_of_context


write_checkpoint -force -noxdef greyScale.dcp

catch { report_utilization -file greyScale_utilization_synth.rpt -pb greyScale_utilization_synth.pb }
