// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xgreyscale.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XGreyscale_CfgInitialize(XGreyscale *InstancePtr, XGreyscale_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XGreyscale_Start(XGreyscale *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XGreyscale_ReadReg(InstancePtr->Axilites_BaseAddress, XGREYSCALE_AXILITES_ADDR_AP_CTRL) & 0x80;
    XGreyscale_WriteReg(InstancePtr->Axilites_BaseAddress, XGREYSCALE_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XGreyscale_IsDone(XGreyscale *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XGreyscale_ReadReg(InstancePtr->Axilites_BaseAddress, XGREYSCALE_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XGreyscale_IsIdle(XGreyscale *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XGreyscale_ReadReg(InstancePtr->Axilites_BaseAddress, XGREYSCALE_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XGreyscale_IsReady(XGreyscale *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XGreyscale_ReadReg(InstancePtr->Axilites_BaseAddress, XGREYSCALE_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XGreyscale_EnableAutoRestart(XGreyscale *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XGreyscale_WriteReg(InstancePtr->Axilites_BaseAddress, XGREYSCALE_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XGreyscale_DisableAutoRestart(XGreyscale *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XGreyscale_WriteReg(InstancePtr->Axilites_BaseAddress, XGREYSCALE_AXILITES_ADDR_AP_CTRL, 0);
}

u32 XGreyscale_Get_pixelInput_BaseAddress(XGreyscale *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XGREYSCALE_AXILITES_ADDR_PIXELINPUT_BASE);
}

u32 XGreyscale_Get_pixelInput_HighAddress(XGreyscale *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XGREYSCALE_AXILITES_ADDR_PIXELINPUT_HIGH);
}

u32 XGreyscale_Get_pixelInput_TotalBytes(XGreyscale *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XGREYSCALE_AXILITES_ADDR_PIXELINPUT_HIGH - XGREYSCALE_AXILITES_ADDR_PIXELINPUT_BASE + 1);
}

u32 XGreyscale_Get_pixelInput_BitWidth(XGreyscale *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XGREYSCALE_AXILITES_WIDTH_PIXELINPUT;
}

u32 XGreyscale_Get_pixelInput_Depth(XGreyscale *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XGREYSCALE_AXILITES_DEPTH_PIXELINPUT;
}

u32 XGreyscale_Write_pixelInput_Words(XGreyscale *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XGREYSCALE_AXILITES_ADDR_PIXELINPUT_HIGH - XGREYSCALE_AXILITES_ADDR_PIXELINPUT_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Axilites_BaseAddress + XGREYSCALE_AXILITES_ADDR_PIXELINPUT_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XGreyscale_Read_pixelInput_Words(XGreyscale *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XGREYSCALE_AXILITES_ADDR_PIXELINPUT_HIGH - XGREYSCALE_AXILITES_ADDR_PIXELINPUT_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Axilites_BaseAddress + XGREYSCALE_AXILITES_ADDR_PIXELINPUT_BASE + (offset + i)*4);
    }
    return length;
}

u32 XGreyscale_Write_pixelInput_Bytes(XGreyscale *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XGREYSCALE_AXILITES_ADDR_PIXELINPUT_HIGH - XGREYSCALE_AXILITES_ADDR_PIXELINPUT_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Axilites_BaseAddress + XGREYSCALE_AXILITES_ADDR_PIXELINPUT_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XGreyscale_Read_pixelInput_Bytes(XGreyscale *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XGREYSCALE_AXILITES_ADDR_PIXELINPUT_HIGH - XGREYSCALE_AXILITES_ADDR_PIXELINPUT_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Axilites_BaseAddress + XGREYSCALE_AXILITES_ADDR_PIXELINPUT_BASE + offset + i);
    }
    return length;
}

u32 XGreyscale_Get_pixelOutput_BaseAddress(XGreyscale *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XGREYSCALE_AXILITES_ADDR_PIXELOUTPUT_BASE);
}

u32 XGreyscale_Get_pixelOutput_HighAddress(XGreyscale *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XGREYSCALE_AXILITES_ADDR_PIXELOUTPUT_HIGH);
}

u32 XGreyscale_Get_pixelOutput_TotalBytes(XGreyscale *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XGREYSCALE_AXILITES_ADDR_PIXELOUTPUT_HIGH - XGREYSCALE_AXILITES_ADDR_PIXELOUTPUT_BASE + 1);
}

u32 XGreyscale_Get_pixelOutput_BitWidth(XGreyscale *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XGREYSCALE_AXILITES_WIDTH_PIXELOUTPUT;
}

u32 XGreyscale_Get_pixelOutput_Depth(XGreyscale *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XGREYSCALE_AXILITES_DEPTH_PIXELOUTPUT;
}

u32 XGreyscale_Write_pixelOutput_Words(XGreyscale *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XGREYSCALE_AXILITES_ADDR_PIXELOUTPUT_HIGH - XGREYSCALE_AXILITES_ADDR_PIXELOUTPUT_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Axilites_BaseAddress + XGREYSCALE_AXILITES_ADDR_PIXELOUTPUT_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XGreyscale_Read_pixelOutput_Words(XGreyscale *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XGREYSCALE_AXILITES_ADDR_PIXELOUTPUT_HIGH - XGREYSCALE_AXILITES_ADDR_PIXELOUTPUT_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Axilites_BaseAddress + XGREYSCALE_AXILITES_ADDR_PIXELOUTPUT_BASE + (offset + i)*4);
    }
    return length;
}

u32 XGreyscale_Write_pixelOutput_Bytes(XGreyscale *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XGREYSCALE_AXILITES_ADDR_PIXELOUTPUT_HIGH - XGREYSCALE_AXILITES_ADDR_PIXELOUTPUT_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Axilites_BaseAddress + XGREYSCALE_AXILITES_ADDR_PIXELOUTPUT_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XGreyscale_Read_pixelOutput_Bytes(XGreyscale *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XGREYSCALE_AXILITES_ADDR_PIXELOUTPUT_HIGH - XGREYSCALE_AXILITES_ADDR_PIXELOUTPUT_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Axilites_BaseAddress + XGREYSCALE_AXILITES_ADDR_PIXELOUTPUT_BASE + offset + i);
    }
    return length;
}

void XGreyscale_InterruptGlobalEnable(XGreyscale *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XGreyscale_WriteReg(InstancePtr->Axilites_BaseAddress, XGREYSCALE_AXILITES_ADDR_GIE, 1);
}

void XGreyscale_InterruptGlobalDisable(XGreyscale *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XGreyscale_WriteReg(InstancePtr->Axilites_BaseAddress, XGREYSCALE_AXILITES_ADDR_GIE, 0);
}

void XGreyscale_InterruptEnable(XGreyscale *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XGreyscale_ReadReg(InstancePtr->Axilites_BaseAddress, XGREYSCALE_AXILITES_ADDR_IER);
    XGreyscale_WriteReg(InstancePtr->Axilites_BaseAddress, XGREYSCALE_AXILITES_ADDR_IER, Register | Mask);
}

void XGreyscale_InterruptDisable(XGreyscale *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XGreyscale_ReadReg(InstancePtr->Axilites_BaseAddress, XGREYSCALE_AXILITES_ADDR_IER);
    XGreyscale_WriteReg(InstancePtr->Axilites_BaseAddress, XGREYSCALE_AXILITES_ADDR_IER, Register & (~Mask));
}

void XGreyscale_InterruptClear(XGreyscale *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XGreyscale_WriteReg(InstancePtr->Axilites_BaseAddress, XGREYSCALE_AXILITES_ADDR_ISR, Mask);
}

u32 XGreyscale_InterruptGetEnabled(XGreyscale *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XGreyscale_ReadReg(InstancePtr->Axilites_BaseAddress, XGREYSCALE_AXILITES_ADDR_IER);
}

u32 XGreyscale_InterruptGetStatus(XGreyscale *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XGreyscale_ReadReg(InstancePtr->Axilites_BaseAddress, XGREYSCALE_AXILITES_ADDR_ISR);
}

