// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xtestflow.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XTestflow_CfgInitialize(XTestflow *InstancePtr, XTestflow_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Axilites_BaseAddress = ConfigPtr->Axilites_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XTestflow_Start(XTestflow *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTestflow_ReadReg(InstancePtr->Axilites_BaseAddress, XTESTFLOW_AXILITES_ADDR_AP_CTRL) & 0x80;
    XTestflow_WriteReg(InstancePtr->Axilites_BaseAddress, XTESTFLOW_AXILITES_ADDR_AP_CTRL, Data | 0x01);
}

u32 XTestflow_IsDone(XTestflow *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTestflow_ReadReg(InstancePtr->Axilites_BaseAddress, XTESTFLOW_AXILITES_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XTestflow_IsIdle(XTestflow *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTestflow_ReadReg(InstancePtr->Axilites_BaseAddress, XTESTFLOW_AXILITES_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XTestflow_IsReady(XTestflow *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XTestflow_ReadReg(InstancePtr->Axilites_BaseAddress, XTESTFLOW_AXILITES_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XTestflow_EnableAutoRestart(XTestflow *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTestflow_WriteReg(InstancePtr->Axilites_BaseAddress, XTESTFLOW_AXILITES_ADDR_AP_CTRL, 0x80);
}

void XTestflow_DisableAutoRestart(XTestflow *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTestflow_WriteReg(InstancePtr->Axilites_BaseAddress, XTESTFLOW_AXILITES_ADDR_AP_CTRL, 0);
}

u32 XTestflow_Get_a_BaseAddress(XTestflow *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XTESTFLOW_AXILITES_ADDR_A_BASE);
}

u32 XTestflow_Get_a_HighAddress(XTestflow *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XTESTFLOW_AXILITES_ADDR_A_HIGH);
}

u32 XTestflow_Get_a_TotalBytes(XTestflow *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XTESTFLOW_AXILITES_ADDR_A_HIGH - XTESTFLOW_AXILITES_ADDR_A_BASE + 1);
}

u32 XTestflow_Get_a_BitWidth(XTestflow *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XTESTFLOW_AXILITES_WIDTH_A;
}

u32 XTestflow_Get_a_Depth(XTestflow *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XTESTFLOW_AXILITES_DEPTH_A;
}

u32 XTestflow_Write_a_Words(XTestflow *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XTESTFLOW_AXILITES_ADDR_A_HIGH - XTESTFLOW_AXILITES_ADDR_A_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Axilites_BaseAddress + XTESTFLOW_AXILITES_ADDR_A_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XTestflow_Read_a_Words(XTestflow *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XTESTFLOW_AXILITES_ADDR_A_HIGH - XTESTFLOW_AXILITES_ADDR_A_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Axilites_BaseAddress + XTESTFLOW_AXILITES_ADDR_A_BASE + (offset + i)*4);
    }
    return length;
}

u32 XTestflow_Write_a_Bytes(XTestflow *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XTESTFLOW_AXILITES_ADDR_A_HIGH - XTESTFLOW_AXILITES_ADDR_A_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Axilites_BaseAddress + XTESTFLOW_AXILITES_ADDR_A_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XTestflow_Read_a_Bytes(XTestflow *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XTESTFLOW_AXILITES_ADDR_A_HIGH - XTESTFLOW_AXILITES_ADDR_A_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Axilites_BaseAddress + XTESTFLOW_AXILITES_ADDR_A_BASE + offset + i);
    }
    return length;
}

u32 XTestflow_Get_b_BaseAddress(XTestflow *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XTESTFLOW_AXILITES_ADDR_B_BASE);
}

u32 XTestflow_Get_b_HighAddress(XTestflow *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->Axilites_BaseAddress + XTESTFLOW_AXILITES_ADDR_B_HIGH);
}

u32 XTestflow_Get_b_TotalBytes(XTestflow *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XTESTFLOW_AXILITES_ADDR_B_HIGH - XTESTFLOW_AXILITES_ADDR_B_BASE + 1);
}

u32 XTestflow_Get_b_BitWidth(XTestflow *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XTESTFLOW_AXILITES_WIDTH_B;
}

u32 XTestflow_Get_b_Depth(XTestflow *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XTESTFLOW_AXILITES_DEPTH_B;
}

u32 XTestflow_Write_b_Words(XTestflow *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XTESTFLOW_AXILITES_ADDR_B_HIGH - XTESTFLOW_AXILITES_ADDR_B_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->Axilites_BaseAddress + XTESTFLOW_AXILITES_ADDR_B_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XTestflow_Read_b_Words(XTestflow *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XTESTFLOW_AXILITES_ADDR_B_HIGH - XTESTFLOW_AXILITES_ADDR_B_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->Axilites_BaseAddress + XTESTFLOW_AXILITES_ADDR_B_BASE + (offset + i)*4);
    }
    return length;
}

u32 XTestflow_Write_b_Bytes(XTestflow *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XTESTFLOW_AXILITES_ADDR_B_HIGH - XTESTFLOW_AXILITES_ADDR_B_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->Axilites_BaseAddress + XTESTFLOW_AXILITES_ADDR_B_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XTestflow_Read_b_Bytes(XTestflow *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XTESTFLOW_AXILITES_ADDR_B_HIGH - XTESTFLOW_AXILITES_ADDR_B_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->Axilites_BaseAddress + XTESTFLOW_AXILITES_ADDR_B_BASE + offset + i);
    }
    return length;
}

void XTestflow_InterruptGlobalEnable(XTestflow *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTestflow_WriteReg(InstancePtr->Axilites_BaseAddress, XTESTFLOW_AXILITES_ADDR_GIE, 1);
}

void XTestflow_InterruptGlobalDisable(XTestflow *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTestflow_WriteReg(InstancePtr->Axilites_BaseAddress, XTESTFLOW_AXILITES_ADDR_GIE, 0);
}

void XTestflow_InterruptEnable(XTestflow *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XTestflow_ReadReg(InstancePtr->Axilites_BaseAddress, XTESTFLOW_AXILITES_ADDR_IER);
    XTestflow_WriteReg(InstancePtr->Axilites_BaseAddress, XTESTFLOW_AXILITES_ADDR_IER, Register | Mask);
}

void XTestflow_InterruptDisable(XTestflow *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XTestflow_ReadReg(InstancePtr->Axilites_BaseAddress, XTESTFLOW_AXILITES_ADDR_IER);
    XTestflow_WriteReg(InstancePtr->Axilites_BaseAddress, XTESTFLOW_AXILITES_ADDR_IER, Register & (~Mask));
}

void XTestflow_InterruptClear(XTestflow *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XTestflow_WriteReg(InstancePtr->Axilites_BaseAddress, XTESTFLOW_AXILITES_ADDR_ISR, Mask);
}

u32 XTestflow_InterruptGetEnabled(XTestflow *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XTestflow_ReadReg(InstancePtr->Axilites_BaseAddress, XTESTFLOW_AXILITES_ADDR_IER);
}

u32 XTestflow_InterruptGetStatus(XTestflow *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XTestflow_ReadReg(InstancePtr->Axilites_BaseAddress, XTESTFLOW_AXILITES_ADDR_ISR);
}

