// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// AXILiteS
// 0x000 : Control signals
//         bit 0  - ap_start (Read/Write/COH)
//         bit 1  - ap_done (Read/COR)
//         bit 2  - ap_idle (Read)
//         bit 3  - ap_ready (Read)
//         bit 7  - auto_restart (Read/Write)
//         others - reserved
// 0x004 : Global Interrupt Enable Register
//         bit 0  - Global Interrupt Enable (Read/Write)
//         others - reserved
// 0x008 : IP Interrupt Enable Register (Read/Write)
//         bit 0  - Channel 0 (ap_done)
//         bit 1  - Channel 1 (ap_ready)
//         others - reserved
// 0x00c : IP Interrupt Status Register (Read/TOW)
//         bit 0  - Channel 0 (ap_done)
//         bit 1  - Channel 1 (ap_ready)
//         others - reserved
// 0x200 ~
// 0x3ff : Memory 'a' (450 * 8b)
//         Word n : bit [ 7: 0] - a[4n]
//                  bit [15: 8] - a[4n+1]
//                  bit [23:16] - a[4n+2]
//                  bit [31:24] - a[4n+3]
// 0x400 ~
// 0x40f : Memory 'b' (10 * 8b)
//         Word n : bit [ 7: 0] - b[4n]
//                  bit [15: 8] - b[4n+1]
//                  bit [23:16] - b[4n+2]
//                  bit [31:24] - b[4n+3]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XTESTFLOW_AXILITES_ADDR_AP_CTRL 0x000
#define XTESTFLOW_AXILITES_ADDR_GIE     0x004
#define XTESTFLOW_AXILITES_ADDR_IER     0x008
#define XTESTFLOW_AXILITES_ADDR_ISR     0x00c
#define XTESTFLOW_AXILITES_ADDR_A_BASE  0x200
#define XTESTFLOW_AXILITES_ADDR_A_HIGH  0x3ff
#define XTESTFLOW_AXILITES_WIDTH_A      8
#define XTESTFLOW_AXILITES_DEPTH_A      450
#define XTESTFLOW_AXILITES_ADDR_B_BASE  0x400
#define XTESTFLOW_AXILITES_ADDR_B_HIGH  0x40f
#define XTESTFLOW_AXILITES_WIDTH_B      8
#define XTESTFLOW_AXILITES_DEPTH_B      10

