// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.2
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _greyScale_HH_
#define _greyScale_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "greyScale_dadd_64bkb.h"
#include "greyScale_dmul_64cud.h"
#include "greyScale_sitodp_dEe.h"
#include "greyScale_AXILiteS_s_axi.h"

namespace ap_rtl {

template<unsigned int C_S_AXI_AXILITES_ADDR_WIDTH = 13,
         unsigned int C_S_AXI_AXILITES_DATA_WIDTH = 32>
struct greyScale : public sc_module {
    // Port declarations 20
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst_n;
    sc_in< sc_logic > s_axi_AXILiteS_AWVALID;
    sc_out< sc_logic > s_axi_AXILiteS_AWREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_ADDR_WIDTH> > s_axi_AXILiteS_AWADDR;
    sc_in< sc_logic > s_axi_AXILiteS_WVALID;
    sc_out< sc_logic > s_axi_AXILiteS_WREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH> > s_axi_AXILiteS_WDATA;
    sc_in< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH/8> > s_axi_AXILiteS_WSTRB;
    sc_in< sc_logic > s_axi_AXILiteS_ARVALID;
    sc_out< sc_logic > s_axi_AXILiteS_ARREADY;
    sc_in< sc_uint<C_S_AXI_AXILITES_ADDR_WIDTH> > s_axi_AXILiteS_ARADDR;
    sc_out< sc_logic > s_axi_AXILiteS_RVALID;
    sc_in< sc_logic > s_axi_AXILiteS_RREADY;
    sc_out< sc_uint<C_S_AXI_AXILITES_DATA_WIDTH> > s_axi_AXILiteS_RDATA;
    sc_out< sc_lv<2> > s_axi_AXILiteS_RRESP;
    sc_out< sc_logic > s_axi_AXILiteS_BVALID;
    sc_in< sc_logic > s_axi_AXILiteS_BREADY;
    sc_out< sc_lv<2> > s_axi_AXILiteS_BRESP;
    sc_out< sc_logic > interrupt;
    sc_signal< sc_logic > ap_var_for_const0;
    sc_signal< sc_lv<64> > ap_var_for_const1;


    // Module declarations
    greyScale(sc_module_name name);
    SC_HAS_PROCESS(greyScale);

    ~greyScale();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    greyScale_AXILiteS_s_axi<C_S_AXI_AXILITES_ADDR_WIDTH,C_S_AXI_AXILITES_DATA_WIDTH>* greyScale_AXILiteS_s_axi_U;
    greyScale_dadd_64bkb<1,5,64,64,64>* greyScale_dadd_64bkb_U0;
    greyScale_dmul_64cud<1,6,64,64,64>* greyScale_dmul_64cud_U1;
    greyScale_dmul_64cud<1,6,64,64,64>* greyScale_dmul_64cud_U2;
    greyScale_sitodp_dEe<1,6,32,64>* greyScale_sitodp_dEe_U3;
    greyScale_sitodp_dEe<1,6,32,64>* greyScale_sitodp_dEe_U4;
    sc_signal< sc_logic > ap_rst_n_inv;
    sc_signal< sc_logic > ap_start;
    sc_signal< sc_logic > ap_done;
    sc_signal< sc_logic > ap_idle;
    sc_signal< sc_lv<31> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_logic > ap_ready;
    sc_signal< sc_lv<11> > pixelInput_address0;
    sc_signal< sc_logic > pixelInput_ce0;
    sc_signal< sc_lv<8> > pixelInput_q0;
    sc_signal< sc_lv<11> > pixelOutput_address0;
    sc_signal< sc_logic > pixelOutput_ce0;
    sc_signal< sc_logic > pixelOutput_we0;
    sc_signal< sc_lv<8> > pixelOutput_d0;
    sc_signal< sc_lv<8> > reg_165;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<64> > grp_fu_148_p2;
    sc_signal< sc_lv<64> > reg_169;
    sc_signal< sc_logic > ap_CS_fsm_state16;
    sc_signal< sc_logic > ap_CS_fsm_state21;
    sc_signal< sc_lv<64> > grp_fu_144_p2;
    sc_signal< sc_lv<64> > reg_175;
    sc_signal< sc_logic > ap_CS_fsm_state26;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > icmp_fu_193_p2;
    sc_signal< sc_lv<12> > tmp_7_fu_203_p1;
    sc_signal< sc_lv<12> > tmp_7_reg_411;
    sc_signal< sc_lv<32> > sum2_cast_fu_212_p1;
    sc_signal< sc_lv<32> > sum2_cast_reg_417;
    sc_signal< sc_lv<8> > pixelInput_load_1_reg_427;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<32> > tmp_13_fu_217_p1;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<32> > sum4_cast_fu_231_p1;
    sc_signal< sc_lv<32> > sum4_cast_reg_442;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<64> > grp_fu_159_p1;
    sc_signal< sc_lv<64> > tmp_s_reg_452;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_lv<64> > grp_fu_162_p1;
    sc_signal< sc_lv<64> > tmp_2_reg_457;
    sc_signal< sc_lv<32> > tmp_15_fu_236_p1;
    sc_signal< sc_lv<64> > tmp_5_reg_467;
    sc_signal< sc_logic > ap_CS_fsm_state15;
    sc_signal< sc_lv<64> > grp_fu_153_p2;
    sc_signal< sc_lv<64> > tmp_3_reg_472;
    sc_signal< sc_lv<1> > p_Result_s_reg_477;
    sc_signal< sc_logic > ap_CS_fsm_state27;
    sc_signal< sc_lv<52> > loc_V_1_fu_263_p1;
    sc_signal< sc_lv<52> > loc_V_1_reg_482;
    sc_signal< sc_lv<1> > isNeg_fu_277_p3;
    sc_signal< sc_lv<1> > isNeg_reg_487;
    sc_signal< sc_lv<12> > sh_assign_1_fu_295_p3;
    sc_signal< sc_lv<12> > sh_assign_1_reg_492;
    sc_signal< sc_lv<8> > tmp_12_fu_361_p3;
    sc_signal< sc_lv<8> > tmp_12_reg_497;
    sc_signal< sc_logic > ap_CS_fsm_state28;
    sc_signal< sc_lv<8> > tmp_9_fu_373_p3;
    sc_signal< sc_lv<8> > tmp_9_reg_503;
    sc_signal< sc_logic > ap_CS_fsm_state29;
    sc_signal< sc_logic > ap_CS_fsm_state30;
    sc_signal< sc_logic > ap_CS_fsm_state31;
    sc_signal< sc_lv<32> > pixelStart_1_fu_84;
    sc_signal< sc_lv<32> > pixelStart_fu_380_p2;
    sc_signal< sc_lv<64> > grp_fu_144_p0;
    sc_signal< sc_lv<64> > grp_fu_144_p1;
    sc_signal< sc_logic > ap_CS_fsm_state17;
    sc_signal< sc_logic > ap_CS_fsm_state22;
    sc_signal< sc_lv<64> > grp_fu_148_p0;
    sc_signal< sc_lv<64> > grp_fu_148_p1;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_lv<32> > grp_fu_159_p0;
    sc_signal< sc_lv<32> > grp_fu_162_p0;
    sc_signal< sc_lv<30> > tmp_fu_183_p4;
    sc_signal< sc_lv<12> > sum2_fu_207_p2;
    sc_signal< sc_lv<12> > sum4_fu_226_p2;
    sc_signal< sc_lv<64> > p_Val2_s_fu_241_p1;
    sc_signal< sc_lv<11> > loc_V_fu_253_p4;
    sc_signal< sc_lv<12> > tmp_i_i_i_i_cast1_fu_267_p1;
    sc_signal< sc_lv<12> > sh_assign_fu_271_p2;
    sc_signal< sc_lv<11> > tmp_3_i_i_i_fu_285_p2;
    sc_signal< sc_lv<12> > tmp_3_i_i_i_cast_fu_291_p1;
    sc_signal< sc_lv<54> > tmp_1_i_i_i_fu_303_p4;
    sc_signal< sc_lv<32> > sh_assign_1_cast_fu_316_p1;
    sc_signal< sc_lv<54> > tmp_5_i_i_i_cast_fu_323_p1;
    sc_signal< sc_lv<137> > tmp_1_i_i_i_cast_fu_312_p1;
    sc_signal< sc_lv<137> > tmp_5_i_i_i_fu_319_p1;
    sc_signal< sc_lv<54> > tmp_6_i_i_i_fu_327_p2;
    sc_signal< sc_lv<1> > tmp_19_fu_339_p3;
    sc_signal< sc_lv<137> > tmp_8_i_i_i_fu_333_p2;
    sc_signal< sc_lv<8> > tmp_10_fu_347_p1;
    sc_signal< sc_lv<8> > tmp_11_fu_351_p4;
    sc_signal< sc_lv<8> > tmp_8_fu_368_p2;
    sc_signal< sc_lv<31> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<31> ap_ST_fsm_state1;
    static const sc_lv<31> ap_ST_fsm_state2;
    static const sc_lv<31> ap_ST_fsm_state3;
    static const sc_lv<31> ap_ST_fsm_state4;
    static const sc_lv<31> ap_ST_fsm_state5;
    static const sc_lv<31> ap_ST_fsm_state6;
    static const sc_lv<31> ap_ST_fsm_state7;
    static const sc_lv<31> ap_ST_fsm_state8;
    static const sc_lv<31> ap_ST_fsm_state9;
    static const sc_lv<31> ap_ST_fsm_state10;
    static const sc_lv<31> ap_ST_fsm_state11;
    static const sc_lv<31> ap_ST_fsm_state12;
    static const sc_lv<31> ap_ST_fsm_state13;
    static const sc_lv<31> ap_ST_fsm_state14;
    static const sc_lv<31> ap_ST_fsm_state15;
    static const sc_lv<31> ap_ST_fsm_state16;
    static const sc_lv<31> ap_ST_fsm_state17;
    static const sc_lv<31> ap_ST_fsm_state18;
    static const sc_lv<31> ap_ST_fsm_state19;
    static const sc_lv<31> ap_ST_fsm_state20;
    static const sc_lv<31> ap_ST_fsm_state21;
    static const sc_lv<31> ap_ST_fsm_state22;
    static const sc_lv<31> ap_ST_fsm_state23;
    static const sc_lv<31> ap_ST_fsm_state24;
    static const sc_lv<31> ap_ST_fsm_state25;
    static const sc_lv<31> ap_ST_fsm_state26;
    static const sc_lv<31> ap_ST_fsm_state27;
    static const sc_lv<31> ap_ST_fsm_state28;
    static const sc_lv<31> ap_ST_fsm_state29;
    static const sc_lv<31> ap_ST_fsm_state30;
    static const sc_lv<31> ap_ST_fsm_state31;
    static const sc_lv<32> ap_const_lv32_0;
    static const int C_S_AXI_DATA_WIDTH;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_14;
    static const sc_lv<32> ap_const_lv32_19;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<32> ap_const_lv32_1A;
    static const sc_lv<32> ap_const_lv32_1B;
    static const sc_lv<32> ap_const_lv32_1C;
    static const sc_lv<32> ap_const_lv32_1D;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_15;
    static const sc_lv<64> ap_const_lv64_3FBC28F5C28F5C29;
    static const sc_lv<64> ap_const_lv64_3FD3333333333333;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<64> ap_const_lv64_3FE2E147AE147AE1;
    static const sc_lv<32> ap_const_lv32_1F;
    static const sc_lv<30> ap_const_lv30_0;
    static const sc_lv<12> ap_const_lv12_1;
    static const sc_lv<12> ap_const_lv12_2;
    static const sc_lv<32> ap_const_lv32_3F;
    static const sc_lv<32> ap_const_lv32_34;
    static const sc_lv<32> ap_const_lv32_3E;
    static const sc_lv<12> ap_const_lv12_C01;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<11> ap_const_lv11_3FF;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_35;
    static const sc_lv<32> ap_const_lv32_3C;
    static const sc_lv<8> ap_const_lv8_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const1();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state15();
    void thread_ap_CS_fsm_state16();
    void thread_ap_CS_fsm_state17();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state21();
    void thread_ap_CS_fsm_state22();
    void thread_ap_CS_fsm_state26();
    void thread_ap_CS_fsm_state27();
    void thread_ap_CS_fsm_state28();
    void thread_ap_CS_fsm_state29();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state30();
    void thread_ap_CS_fsm_state31();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_ap_rst_n_inv();
    void thread_grp_fu_144_p0();
    void thread_grp_fu_144_p1();
    void thread_grp_fu_148_p0();
    void thread_grp_fu_148_p1();
    void thread_grp_fu_159_p0();
    void thread_grp_fu_162_p0();
    void thread_icmp_fu_193_p2();
    void thread_isNeg_fu_277_p3();
    void thread_loc_V_1_fu_263_p1();
    void thread_loc_V_fu_253_p4();
    void thread_p_Val2_s_fu_241_p1();
    void thread_pixelInput_address0();
    void thread_pixelInput_ce0();
    void thread_pixelOutput_address0();
    void thread_pixelOutput_ce0();
    void thread_pixelOutput_d0();
    void thread_pixelOutput_we0();
    void thread_pixelStart_fu_380_p2();
    void thread_sh_assign_1_cast_fu_316_p1();
    void thread_sh_assign_1_fu_295_p3();
    void thread_sh_assign_fu_271_p2();
    void thread_sum2_cast_fu_212_p1();
    void thread_sum2_fu_207_p2();
    void thread_sum4_cast_fu_231_p1();
    void thread_sum4_fu_226_p2();
    void thread_tmp_10_fu_347_p1();
    void thread_tmp_11_fu_351_p4();
    void thread_tmp_12_fu_361_p3();
    void thread_tmp_13_fu_217_p1();
    void thread_tmp_15_fu_236_p1();
    void thread_tmp_19_fu_339_p3();
    void thread_tmp_1_i_i_i_cast_fu_312_p1();
    void thread_tmp_1_i_i_i_fu_303_p4();
    void thread_tmp_3_i_i_i_cast_fu_291_p1();
    void thread_tmp_3_i_i_i_fu_285_p2();
    void thread_tmp_5_i_i_i_cast_fu_323_p1();
    void thread_tmp_5_i_i_i_fu_319_p1();
    void thread_tmp_6_i_i_i_fu_327_p2();
    void thread_tmp_7_fu_203_p1();
    void thread_tmp_8_fu_368_p2();
    void thread_tmp_8_i_i_i_fu_333_p2();
    void thread_tmp_9_fu_373_p3();
    void thread_tmp_fu_183_p4();
    void thread_tmp_i_i_i_i_cast1_fu_267_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
